name: pp
description: Displaying a list of popular people (actors, directors ..etc) with infinite scrolling.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # UI
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1

  # Remote API
  dio: ^5.3.3
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1

  # Value equality
  equatable: ^2.0.5

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5

  # Functional programming thingies
  dartz: ^0.10.1

  # Other
  intl: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  json_serializable: ^6.7.1
  build_runner: ^2.4.6


flutter:
  uses-material-design: true